### ISSUE TITLE
With SassyStudio enabled keywords and punctuations in js/C# become bold

### ISSUE THREAD

**Issue by mdonatas** [darrenkopp/SassyStudio#23]
http://img202.imageshack.us/img202/3135/14g8.png

After disabling SassyStudio in extensions and restarting VS it goes back to normal.

**Comment by srikanthpullela** [comment]
s

**Comment by srikanthpullela** [comment]
Hi All, I am facing one issue that i have installed SassyStudio and its working fine , after restarting my visual studio when i write some code and try to save its not updating. if you create new one and write some code works fine , i dont knw why its happening to existed files.
