### ISSUE TITLE
Visual Studio crashes when attempting to compile

### ISSUE THREAD

**Issue by RoboAndie** [darrenkopp/SassyStudio#81]
I had a heck of a time trying to figure out why Visual Studio kept crashing every time it tried to compile my Sass using the SassyStudio compiler. Turns out I was using an old Bootstrap mixin with some incorrectly-escaped characters. It would be fine to throw an error for something like this, but crashing the whole program is a bit extreme. I'm hoping to avoid one of my back end developers running into the same thing - they're already annoyed enough with Sass. :/

Here's the line that caused the issue: `font: #{0/0} a;`

Changing the line to this fixed it: `font: 0/0 a;`

Thanks!

**Comment by darrenkopp** [comment]
Unfortunately, I don't do the actual compilation, I rely on [libsass](https://github.com/sass/libsass) for that. I just updated it to the latest version this morning, so hopefully that resolves the issue, otherwise I would suggest opening a bug ticket with them.
